# Generated by Django 4.1.3 on 2023-07-31 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedata',
            name='name',
        ),
    ]
